export const cppOverloadableOperators: Record<string, string> = {
    "operator+": "operatorPlus",
    "operator-": "operatorMinus",
    "operator*": "operatorMultiply",
    "operator/": "operatorDivide",
    "operator%": "operatorModulo",
    "operator++": "operatorIncrement",
    "operator--": "operatorDecrement",
    "operator==": "operatorEquals",
    "operator!=": "operatorNotEquals",
    "operator<": "operatorLessThan",
    "operator<=": "operatorLessThanOrEquals",
    "operator>": "operatorGreaterThan",
    "operator>=": "operatorGreaterThanOrEquals",
    "operator&&": "operatorLogicalAnd",
    "operator||": "operatorLogicalOr",
    "operator!": "operatorLogicalNot",
    "operator&": "operatorBitwiseAnd",
    "operator|": "operatorBitwiseOr",
    "operator^": "operatorBitwiseXor",
    "operator~": "operatorBitwiseNot",
    "operator<<": "operatorLeftShift",
    "operator>>": "operatorRightShift",
    "operator+=": "operatorPlusAssign",
    "operator-=": "operatorMinusAssign",
    "operator*=": "operatorMultiplyAssign",
    "operator/=": "operatorDivideAssign",
    "operator%=": "operatorModuloAssign",
    "operator&=": "operatorBitwiseAndAssign",
    "operator|=": "operatorBitwiseOrAssign",
    "operator^=": "operatorBitwiseXorAssign",
    "operator<<=": "operatorLeftShiftAssign",
    "operator>>=": "operatorRightShiftAssign",
    "operator=": "operatorAssign",
    "operator[]": "operatorSubscript",
    "operator()": "operatorFunctionCall",
    "operator->": "operatorArrow",
    "operator->*": "operatorPointerToMemberArrow",
    "operator,": "operatorComma",
    "operator new": "operatorNew",
    "operator delete": "operatorDelete",
    "operator new[]": "operatorNewArray",
    "operator delete[]": "operatorDeleteArray"
};
